image: openjdk:8-jdk

stages:
  - build
  - test

build_rcs_cis:
  stage: build
  tags:
    - docker
  artifacts:
    when: always
    expire_in: 1 week
    name: "rcs-sdk-${CI_BUILD_REF}"
    paths:
      - build/
  script:
    - ./gradlew clean build
